# Worksheet 1
## Exercise on Functions:

**Task - 1:**

Create a Python program that converts between different units of measurement.
*   The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
*   Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.
*   Conversion Options:
1. Length:
- Convert meters (m) to feet (ft).
- Convert feet (ft) to meters (m).
2. Weight:
- Convert kilograms (kg) to pounds (lbs).
- Convert pounds (lbs) to kilograms (kg).
3. Volume:
- Convert liters (L) to gallons (gal).
- Convert gallons (gal) to liters (L).


In [ ]:
def convert_length(value, from_unit, to_unit):
  """
  Purpose: To convert length from meters(m) to feet(ft) and vice versa

  Parameters:
  value (float): Value to convert
  from_unit (str): Unit to convert from ('m' or 'ft')
  to_unit (str): Unit to convert to ('m' or 'ft')

  Return value:
  float: converted value
  """
  units = {'m', 'ft'}
  if from_unit not in units or to_unit not in units:
    raise ValueError("Invalid units for length conversion. Use 'm' or 'ft'.")

  if from_unit == 'm' and to_unit == 'ft':
    return value * 3.28084  # 1 m = 3.28084 ft
  elif from_unit == 'ft' and to_unit == 'm':
    return value / 3.28084  # 1 ft = 1/3.28084 m
  else:
    raise ValueError("Invalid units for length conversion")

def convert_weight(value, from_unit, to_unit):
  """
  Purpose: To convert weight from kilograms(kg) to pounds(lbs) and vice versa

  Parameters:
  value (float): Value to convert
  from_unit (str): Unit to convert from ('kg' or 'lbs')
  to_unit (str): Unit to convert to ('kg' or 'lbs')

  Return value:
  float: converted value
  """
  units = {'kg', 'lbs'}
  if from_unit not in units or to_unit not in units:
    raise ValueError("Invalid units for weight conversion. Use 'kg' or 'lbs'.")

  if from_unit == 'kg' and to_unit == 'lbs':
    return value * 2.20462  # 1 kg = 2.20462 lbs
  elif from_unit == 'lbs' and to_unit == 'kg':
    return value / 2.20462  # 1 lbs = 1/2.20462 kg
  else:
    raise ValueError("Invalid units for weight conversion")

def convert_volume(value, from_unit, to_unit):
  """
  Purpose: To convert volume from liters(l) to gallons(gal) and vice versa

  Parameters:
  value (float): Value to convert
  from_unit (str): Unit to convert from ('l' or 'gal')
  to_unit (str): Unit to convert to ('l' or 'gal')

  Return value:
  float: converted value
  """
  units = {'l', 'gal'}
  if from_unit not in units or to_unit not in units:
    raise ValueError("Invalid units for volume conversion. Use 'l' or 'gal'.")

  if from_unit == 'l' and to_unit == 'gal':
    return value * 0.264172  # 1 l = 0.264172 gal
  elif from_unit == 'gal' and to_unit == '':
    return value / 0.264172  # 1 gal = 1/0.264172 l
  else:
    raise ValueError("Invalid units for volume conversion")

def main():
  """
  Main function to run the program to convert between different units of measurement
  """
  while True:
    # ask user to choose the type of conversion
    print("\nList of Types of Conversions:")
    print("1. Length (m/ft)")
    print("2. Weight (kg/lbs)")
    print("3. Volume (l/gal)")

    try:
      choice = int(input("\nEnter your choice or 4 to exit: "))

      if choice == 4:
        print("Exiting the program.")
        break

      if choice not in [1, 2, 3]:
        raise ValueError("Invalid choice. Please select a valid conversion type.")

      # ask for value to convert
      while True:
        try:
          value = float(input("Enter the value to be converted: "))
          if value <= 0:
            print("Error: Please enter a positive number.")
            continue
          break
        except ValueError:
          print("Error: Please enter a valid number.")

      # ask for units
      if choice == 1:
        from_unit = input("Enter the unit to convert from (m or ft): ").lower()
        to_unit = input("Enter the unit to convert to (m or ft): ").lower()
        result = convert_length(value, from_unit, to_unit)

      elif choice == 2:
        from_unit = input("Enter the unit to convert from (kg or lbs): ").lower()
        to_unit = input("Enter the unit to convert to (kg or lbs): ").lower()
        result = convert_weight(value, from_unit, to_unit)

      elif choice == 3:
        from_unit = input("Enter the unit to convert from (l or gal): ").lower()
        to_unit = input("Enter the unit to convert to (l or gal): ").lower()
        result = convert_volume(value, from_unit, to_unit)

      # print result
      print(f"\nResult: {value} {from_unit} is equal to {result:.2f} {to_unit}.")
    except ValueError as e:
      print(f"Error: {e}")
    except Exception as e:
      print(f"Unexpected error: {e}")

main()


List of Types of Conversions:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter your choice or 4 to exit: 0
Error: Invalid choice. Please select a valid conversion type.

List of Types of Conversions:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter your choice or 4 to exit: 1
Enter the value to be converted: -3
Error: Please enter a positive number.
Enter the value to be converted: b
Error: Please enter a valid number.
Enter the value to be converted: 999
Enter the unit to convert from (m or ft): m
Enter the unit to convert to (m or ft): feet
Error: Invalid units for length conversion. Use 'm' or 'ft'.

List of Types of Conversions:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/gal)

Enter your choice or 4 to exit: 1
Enter the value to be converted: 999
Enter the unit to convert from (m or ft): m
Enter the unit to convert to (m or ft): ft

Result: 999.0 m is equal to 3277.56 ft.

List of Types of Conversions:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (l/

**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.
*   The program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers)
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
*   Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
# calculates the sum of given list of numbers
def add(numbers):
  """
  Purpose: To calculate the sum of a list of numbers

  Parameters:
  numbers: A list of numeric values

  Return value:
  float: Sum of the numbers in the list
  """
  return sum(numbers)

# calculates the average of given list of numbers
def average(numbers):
  """
  Purpose: To calculate the average(mean) of a list of numbers

  Parameters:
  numbers: A list of numeric values

  Return value:
  float: Average of the numbers in the list
  """
  return sum(numbers) / len(numbers)

# finds the maximum number in the given list
def maximum(numbers):
  """
  Purpose: To find the maximum number in a list

  Parameters:
  numbers: A list of numeric values

  Return value:
  float: Maximum number in the list
  """
  return max(numbers)

# finds the minimum number in the given list
def minimum(numbers):
  """
  Purpose: To find the minimum number in a list

  Parameters:
  numbers: A list of numeric values

  Return value:
  float: Minimum number in the list
  """
  return min(numbers)

def main():
  """
  Main function that prompts the user to select an operation and input a list of numbers.
  Performs the selected operation and displays the result.
  Handles errors for invalid inputs and empty lists.
  """
  while True:
    print("\nList of Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
      # ask user to choose an operation
      choice = int(input("Enter your choice or 5 to exit: "))

      if choice == 5:
        print("Exiting the program.")
        break

      if choice not in [1, 2, 3, 4]:
        print("Invalid choice. Please select a valid option.")
        continue
      # ask user for a list of numbers
      numbers_input = input("Enter numbers separated by spaces: ")
      numbers_list = [float(num) for num in numbers_input.split()]

      if not numbers_list:
        print("Error: The list of numbers cannot be empty.")
        continue

      # perform the selected operation
      if choice == 1:
        result = add(numbers_list)
        print(f"\nSum: {result}")
      elif choice == 2:
        result = average(numbers_list)
        print(f"\nAverage: {result}")
      elif choice == 3:
        result = maximum(numbers_list)
        print(f"\nMaximum: {result}")
      elif choice == 4:
        result = minimum(numbers_list)
        print(f"\nMinimum: {result}")

    except ValueError:
      print("Error: Please enter valid numeric values.")
    except Exception as e:
      print(f"Unexpected error: {e}")

main()


List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: -1
Invalid choice. Please select a valid option.

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 1
Enter numbers separated by spaces: 
Error: The list of numbers cannot be empty.

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 1
Enter numbers separated by spaces: 1 3 5 7 9 11

Sum: 36.0

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 2 4 6 8 10
Error: Please enter valid numeric values.

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 3
Enter numbers separated by spaces: 3 7 1 9 5

Maximum: 9.0

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 5 to exit: 4
Enter numbers separated by spaces: 6 0 4 8 2

Minimum: 0.0

List of Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice or 

## Exercise on List Manipulation:

1. Extract Every Other Element:

  Write a Python function that extracts every other element from a list, starting from the first element.

  Requirements:
- Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].


In [20]:
def extract_every_other(lst):
  return lst[::2]  # selects every other element starting from index 0

input_list = [1, 2, 3, 4, 5, 6]
new_list = extract_every_other(input_list)
print(f"Input List:\n{input_list}\n")
print(f"Every other element of the list:\n{new_list}")

Input List:
[1, 2, 3, 4, 5, 6]

Every other element of the list:
[1, 3, 5]


2. Slice a Sublist:

  Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

  Requirements:
- Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).
- Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [14]:
def get_sublist(lst, start, end):
  return lst[start:end+1]  # add 1 to end to include the last index

input_list = [1, 2, 3, 4, 5, 6]
sublist = get_sublist(input_list, 2, 4)
print(f"Input List:\n{input_list}\n")
print(f"Sublist starting from index 2 to index 4:\n{sublist}")

Input List:
[1, 2, 3, 4, 5, 6]

Sublist starting from index 2 to index 4:
[3, 4, 5]


3. Reverse a List Using Slicing:

  Write a Python function that reverses a list using slicing.

  Requirements:
- Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [15]:
def reverse_list(lst):
  return lst[::-1]  # slicing with step -1 to reverse the list

input_list = [1, 2, 3, 4, 5]
reversed = reverse_list(input_list)
print(f"Input List:\n{input_list}\n")
print(f"Reversed List:\n{reversed}")

Input List:
[1, 2, 3, 4, 5]

Reversed List:
[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

  Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

  Requirements:
- Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
- Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [16]:
def remove_first_last(lst):
  return lst[1:-1]  # slicing from index 1 to second last index

input_list = [1, 2, 3, 4, 5]
sublist = remove_first_last(input_list)
print(f"Input List:\n{input_list}\n")
print(f"List without the first and last elements:\n{sublist}")

Input List:
[1, 2, 3, 4, 5]

List without the first and last elements:
[2, 3, 4]


5. Get the First n Elements:

  Write a Python function that extracts the first n elements from a list.

  Requirements:
- Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.
- Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [17]:
def get_first_n(lst, n):
  return lst[:n]  # except the nth index

input_list = [1, 2, 3, 4, 5]
n = 3
sublist = get_first_n(input_list, n)
print(f"Input List:\n{input_list}\n")
print(f"First {n} elements of the list:\n{sublist}")

Input List:
[1, 2, 3, 4, 5]

First 3 elements of the list:
[1, 2, 3]


6. Extract Elements from the End:

  Write a Python function that extracts the last n elements of a list using slicing.

  Requirements:
- Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.
- Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [18]:
def get_last_n(lst, n):
  return lst[-n:]  # slice from the last n elements

input_list = [1, 2, 3, 4, 5]
n = 2
sublist = get_last_n(input_list, n)
print(f"Input List:\n{input_list}\n")
print(f"Last {n} elements of the list:\n{sublist}")

Input List:
[1, 2, 3, 4, 5]

Last 2 elements of the list:
[4, 5]


7. Extract Elements in Reverse Order:

  Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

  Requirements:
- Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.
- Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [19]:
def reverse_skip(lst):
  return lst[-2::-2]  # start from second last index and skip 1 element in reverse

input_list = [1, 2, 3, 4, 5, 6]
sublist = reverse_skip(input_list)
print(f"Input List:\n{input_list}\n")
print(f"Every other element in reverse order starting from the second last element:\n{sublist}")

Input List:
[1, 2, 3, 4, 5, 6]

Every other element in reverse order starting from the second last element:
[5, 3, 1]


## Exercise on Nested List:

1. Flatten a Nested List:

  Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

  Requirements:
- Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
- Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [21]:
def flatten(lst):
  flattened_list = []
  # loop over the sublists inside lst
  for sublist in lst:
    # loop over each item in the sublist
    for item in sublist:
      flattened_list.append(item) # add each item to flattened_list
  return flattened_list

input_list = [[1, 2], [3, 4], [5]]
single_list = flatten(input_list)
print(f"Input Nested List:\n{input_list}\n")
print(f"Flattened List:\n{single_list}")

Input Nested List:
[[1, 2], [3, 4], [5]]

Flattened List:
[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

  Write a Python function that extracts a specific element from a nested list given its indices.

  Requirements:
- Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.
- Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [22]:
def access_nested_element(lst, indices):
  element = lst
  # loop through each index indices
  for index in indices:
    element = element[index]
  return element

input_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
element = access_nested_element(input_list, indices)
print(f"Input Nested List:\n{input_list}\n")
print(f"Element at index[1,2]: {element}")

Input Nested List:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Element at index[1,2]: 6


3. Sum of All Elements in a Nested List:

  Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

  Requirements:
- Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [23]:
def sum_nested(lst):
  total = 0
  # loop through each item in the list
  for item in lst:
    # check if current item is a nested list
    if type(item) == list:
      total += sum_nested(item) # sum the nested list recursively
    else:
      total += item # else add it to total
  return total

input_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(input_list)
print(f"Input Nested List:\n{input_list}\n")
print(f"Sum of all elements in the nested list: {result}")

Input Nested List:
[[1, 2], [3, [4, 5]], 6]

Sum of all elements in the nested list: 21


4. Remove Specific Element from a Nested List:
  
  Write a Python function that removes all occurrences of a specific element from a nested list.

  Requirements:
- Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.
- Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [24]:
def remove_element(lst, elem):
  result = []
  for item in lst:
    # check if current item is a nested list
    if type(item) == list:
      new_sublist = remove_element(item, elem) # call the function recursively for sublist
      # add the sublist to the result only if it is not tmpty
      if new_sublist:
        result.append(new_sublist)
    # keep the current item if it is not the target element
    elif item != elem:
      result.append(item)
  return result

input_list = [[1, 2], [3, 2], [4, 5]]
element = 2
result = remove_element(input_list, element)
print(f"Input Nested List:\n{input_list}\n")
print(f"Modified list after removing an element:\n{result}")

Input Nested List:
[[1, 2], [3, 2], [4, 5]]

Modified list after removing an element:
[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

  Write a Python function that finds the maximum element in a nested list (regardless of depth).

  Requirements:
- Define a function find max(lst) that takes a nested list lst and returns the maximum element.
- Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [25]:
def find_max(lst):
  max_val = float('-inf')
  for item in lst:
    # check if current item is a nested list
    if type(item) == list:
      max_val = max(max_val, find_max(item)) # find max in the nested list recursively
    else:
      max_val = max(max_val, item) # else compare with max_val
  return max_val

input_list = [[1, 2], [3, [4, 5]], 6]
max_value = find_max(input_list)
print(f"Input Nested List:\n{input_list}\n")
print(f"Maximum element in the nested list: {max_value}")

Input Nested List:
[[1, 2], [3, [4, 5]], 6]

Maximum element in the nested list: 6


6. Count Occurrences of an Element in a Nested List:

  Write a Python function that counts how many times a specific element appears in a nested list.

  Requirements:
- Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.
- Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [26]:
def count_occurrences(lst, elem):
  count = 0
  for item in lst:
    # check if current item is a nested list
    if type(item) == list:
      count += count_occurrences(item, elem)  # call the function recursively for sublist
    elif item == elem:  # if current item the target element, increase the count
      count += 1
  return count

input_list = [[1, 2], [2, 3], [2, 4]]
element = 2
result = count_occurrences(input_list, element)
print(f"Input Nested List:\n{input_list}\n")
print(f"Element {element} occurs {result} times in the nested list.")

Input Nested List:
[[1, 2], [2, 3], [2, 4]]

Element 2 occurs 3 times in the nested list.


7. Flatten a List of Lists of Lists:

  Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

  Requirements:
- Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.
- Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [27]:
def deep_flatten(lst):
  flattened_list = []
  for item in lst:
    # check if current item is a nested list
    if type(item) == list:
      flattened_list.extend(deep_flatten(item)) # call the flatten function recursively and add the flattened result to the list
    else:
      flattened_list.append(item) # else add current item to the list
  return flattened_list

input_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flattened_list = deep_flatten(input_list)
print(f"Input Nested List:\n{input_list}\n")
print(f"Flattened List:\n{flattened_list}")

Input Nested List:
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Flattened List:
[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

  Write a Python function that calculates the average of all elements in a nested list.

  Requirements:
- Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.
- Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [28]:
def average_nested(lst):
  # function to flatten the nested list
  def deep_flatten(lst):
    flattened_list = []
    for item in lst:
      if type(item) == list:
        flattened_list.extend(deep_flatten(item)) # call the flatten function recursively and add the flattened result to the list
      else:
        flattened_list.append(item) # else add current item to the list
    return flattened_list

  # function call to flatten the list
  flattened_list = deep_flatten(lst)

  # calculate and return the average of flattened list
  if flattened_list:
    return sum(flattened_list) / len(flattened_list)
  else:
    return 0

input_list = [[1, 2], [3, 4], [5, 6]]
average = average_nested(input_list)
print(f"Input Nested List:\n{input_list}\n")
print(f"Average of elements in the nested list: {average}")

Input Nested List:
[[1, 2], [3, 4], [5, 6]]

Average of elements in the nested list: 3.5


## Basic Vector and Matrix Operation with Numpy
### Problem - 1: Array Creation:


In [30]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [31]:
empty_arr = np.empty((2,2))
print(f"Empty array of size 2x2:\n{empty_arr}")

Empty array of size 2x2:
[[2.67807814e-316 0.00000000e+000]
 [6.63366353e-310 6.63366344e-310]]


2. Initialize an all one array with size 4X2.

In [32]:
ones_arr = np.ones((4,2))
print(f"All one array of size 4x2:\n{ones_arr}")

All one array of size 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [36]:
arr = np.full((3,2), 5, dtype=int)
print("An array of shape (3,2), 5 as fill value and int data type:\n", arr)

An array of shape (3,2), 5 as fill value and int data type:
 [[5 5]
 [5 5]
 [5 5]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [37]:
print(f"An array of shape (3,2), all zeros, and int data type:\n{np.zeros_like(arr)}")

An array of shape (3,2), all zeros, and int data type:
[[0 0]
 [0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [38]:
print(f"An array of shape (3,2), all ones, and int data type:\n{np.ones_like(arr)}")

An array of shape (3,2), all ones, and int data type:
[[1 1]
 [1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [39]:
new_list = [1,2,3,4]
new_arr = np.array(new_list)
print(f"List: {new_list}")
print(f"Array: {new_arr}")
print(f"Type of array: {type(new_arr)}")

List: [1, 2, 3, 4]
Array: [1 2 3 4]
Type of array: <class 'numpy.ndarray'>


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [40]:
print(f"Array with values ranging from 10 to 49:\n{np.arange(10, 49)}")

Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

In [41]:
array = np.arange(9) # range => 0 to 8
matrix = np.reshape(array, (3,3))
print(f"3X3 matrix with values ranging from 0 to 8:\n{matrix}")

3X3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [42]:
identity = np.eye(3, dtype=int)
print(f"3X3 identity matrix:\n{identity}")

3X3 identity matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [47]:
random_arr = np.random.random(30)
print(f"Random array of size 30:\n{random_arr}")
mean = np.mean(random_arr)
print(f"\nMean of the array is {mean}.")

Random array of size 30:
[0.26495966 0.31706762 0.40923532 0.89991427 0.67158288 0.56957916
 0.71237126 0.49046966 0.25131227 0.36030834 0.26655097 0.12317707
 0.45167448 0.61473432 0.79918676 0.3158854  0.50910993 0.45994119
 0.04207484 0.0815252  0.45062539 0.6183083  0.30151394 0.06017391
 0.57910345 0.29946657 0.7374929  0.8100856  0.97084433 0.31049259]

Mean of the array is 0.4582922526105491.


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [56]:
random_arr1 = np.random.random((10, 10))
print(f"10X10 array with random values:\n{random_arr1}")
print(f"\nThe minimum value is {np.min(random_arr1)}.")
print(f"\nThe maximum value is {np.max(random_arr1)}.")

10X10 array with random values:
[[0.97954198 0.85367435 0.61279748 0.92096559 0.15874204 0.86836165
  0.35099855 0.1783252  0.01943715 0.40647611]
 [0.70816506 0.16032926 0.10142868 0.73672849 0.87239476 0.29364057
  0.47420647 0.21217883 0.88883955 0.48432969]
 [0.03119323 0.9644606  0.95659936 0.44268771 0.72252825 0.7187605
  0.68448743 0.66921229 0.7317858  0.23839149]
 [0.53459922 0.08017524 0.89277187 0.68764256 0.39366859 0.01999358
  0.91212266 0.17147164 0.4013407  0.15505444]
 [0.07084644 0.27431629 0.97204159 0.05028932 0.16205861 0.95982818
  0.97728715 0.73492411 0.13790027 0.10379646]
 [0.73651428 0.50091427 0.45727888 0.89473769 0.00910794 0.05141668
  0.83971379 0.10050123 0.20004116 0.62118945]
 [0.56579166 0.37653509 0.78682205 0.32586636 0.72499067 0.87360514
  0.04794273 0.15376491 0.60644576 0.26216124]
 [0.17147173 0.19419409 0.32043866 0.26580155 0.22866879 0.725157
  0.38192428 0.59378627 0.76695003 0.26277351]
 [0.89325193 0.26274997 0.83890872 0.68359745 0.616

6. Create a zero array of size 10 and replace 5th element with 1.

In [51]:
zeros_arr = np.zeros(10, dtype=int)
print(f"All zeros array:\n{zeros_arr}")
zeros_arr[4] = 1
print(f"\nNew array:\n{zeros_arr}")

All zeros array:
[0 0 0 0 0 0 0 0 0 0]

New array:
[0 0 0 0 1 0 0 0 0 0]


7. Reverse an array arr = [1,2,0,0,4,0].

In [53]:
arr = np.array([1,2,0,0,4,0])
print(f"Original array:\n{arr}")
reversed = arr[::-1]
print(f"\nReversed array:\n{reversed}")

Original array:
[1 2 0 0 4 0]

Reversed array:
[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [54]:
array = np.ones((7, 7), dtype=int)
array[1:-1, 1:-1]=0
print(f"2d array with 1 on border and 0 inside:\n{array}")

2d array with 1 on border and 0 inside:
[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [55]:
array = np.zeros((8, 8), dtype=int)
array[1::2, ::2]=1
array[::2, 1::2]=1
print(f"A checkerboard pattern 8x8 matrix:\n{array}")

A checkerboard pattern 8x8 matrix:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:


1. Add the two array.

In [57]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Adding x and y:")
add_xy = np.add(x, y)
print(add_xy)
print("\nAdding v and w:")
add_vw = np.add(v, w)
print(add_vw)

Adding x and y:
[[ 6  8]
 [10 13]]

Adding v and w:
[20 22]


2. Subtract the two array.

In [59]:
print("Subtracting y from x:")
subtract_xy = np.subtract(x, y)
print(subtract_xy)
print("\nSubtracting w from v:")
subtract_vw = np.subtract(v, w)
print(subtract_vw)

Subtracting y from x:
[[-4 -4]
 [-4 -3]]

Subtracting w from v:
[-2 -2]


3. Multiply the array with any integers of your choice.

In [60]:
print("Multipliplying x with 2:")
multiply1 = np.dot(x, 2)
print(multiply1)
print("\nMultipliplying y with 3:")
multiply2 = np.dot(y, 3)
print(multiply2)

Multipliplying x with 2:
[[ 2  4]
 [ 6 10]]

Multipliplying y with 3:
[[15 18]
 [21 24]]


4. Find the square of each element of the array.

In [61]:
print("Square of each element of array x:")
squared_arrx = x ** 2
print(squared_arrx)
print("\nSquare of each element of array v:")
squared_arrv = v ** 2
print(squared_arrv)

Square of each element of array x:
[[ 1  4]
 [ 9 25]]

Square of each element of array v:
[ 81 100]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [63]:
print("Dot Products:")
dot_prod_vw = np.dot(v, w)
print("\nv(and)w:", dot_prod_vw)
dot_prod_xv = np.dot(x, v)
print("\nx(and)v:", dot_prod_xv)
dot_prod_xy = np.dot(x, y)
print("\nx(and)y:\n", dot_prod_xy)

Dot Products:

v(and)w: 219

x(and)v: [29 77]

x(and)y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

In [64]:
print("Concatenating x(and)y along row:")
concatenate_row = np.concatenate((x, y), axis=0)
print(concatenate_row)

print("\nConcatenating v(and)w along column:")
concatenate_column = np.concatenate_column = np.vstack((v, w)).T
print(concatenate_column)

Concatenating x(and)y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v(and)w along column:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [65]:
print("\nConcatenating x(and)v:")
concatenate_xv = np.concatenate((x, v), axis=0)
print(concatenate_xv)


Concatenating x(and)v:


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### Error Explanation
We get an error when we try to concatenate x and v directly because their shapes are not compatible. To concatenate any two arrays, their dimensions must align. In this case, the error occurs because one is a 2D array and the other is a 1D array.

### Problem - 4: Matrix Operations:
- For the following arrays:

  A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

  Prove following with Numpy:
  1. Prove A.A−1 = I.
  2. Prove AB ̸= BA.
  3. Prove(AB)T =BTAT.

In [67]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#1
from numpy import linalg

inverse_A = np.linalg.inv(A)
result1 = np.dot(A, inverse_A)
print(f"1. Result of A.A−1:\n{np.round(result1)}")

#2
prod_AB = np.dot(A, B)
prod_BA = np.dot(B, A)

check = np.array_equal(A, B)
print("\n")
if check == True:
  print("2. AB = BA")
else:
  print("2. AB != BA")

#3
transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

prod_BTAT = np.dot(transpose_B, transpose_A)
transpose_AB = np.transpose(prod_AB)

check1 = np.array_equal(transpose_AB, prod_BTAT)
print("\n")
if check1 == True:
  print("3. (AB)T = BT.AT")
else:
  print("3. (AB)T != BT.AT")

1. Result of A.A−1:
[[1. 0.]
 [0. 1.]]


2. AB != BA


3. (AB)T = BT.AT


- Solve the following system of Linear equation using Inverse Methods.

  2x − 3y + z = −1

  x − y + 2z = −3

  3x + y − z = 9

  {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [71]:
# representing the equation in Matrix form
# coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# constant matrix B
B = np.array([-1, -3, 9])

print("Matrix representation of the equation AX = B:")
print("Coefficient matrix A:")
print(A)
print("\nConstant matrix B:")
print(B)

# find the determinant of A
det_A = np.linalg.det(A)

# find the adjugate matrix of A
cofactor_matrix = np.zeros_like(A, dtype=float)

# find the cofactor matrix using a loop
for i in range(A.shape[0]):  # loop over rows
    for j in range(A.shape[1]):  # loop over columns
        # create the minor matrix by deleting the i-th row and j-th column
        minor_matrix = np.delete(np.delete(A, i, axis=0), j, axis=1)
        # find the determinant of the minor matrix and apply the sign
        cofactor_matrix[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor_matrix)

# adjugate matrix is the transpose of cofactor matrix
adjugate_matrix = cofactor_matrix.T

# find the inverse of A
A_inv = adjugate_matrix / det_A

# solve for X: X = A_inv * B
X = np.dot(A_inv, B)

print("\nSolution vector X using inverse method:")
print(X)

Matrix representation of the equation AX = B:
Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant matrix B:
[-1 -3  9]

Solution vector X using inverse method:
[ 2.  1. -2.]


- Now: solve the above equation using np.linalg.inv function. {Explore more about ”linalg” func- tion of Numpy}

In [73]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

inv_A = np.linalg.inv(A)
X = np.dot(inv_A, B)
print("Solution vector X using np.linalg.inv function:")
print(X)

Solution vector X using np.linalg.inv function:
[ 2.  1. -2.]


### Experiment: How Fast is Numpy?

1. Element-wise Addition:
- Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [81]:
import time

list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

# measuring the time for element wise addition using Python lists
start_time = time.time()
result_time = [a+b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise addition using Python lists: {list_time} seconds")

# convert lists to numpy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# measuring time for element-wise addition using numpy arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
array_time = end_time - start_time
print(f"\nTime taken for element-wise addition using Numpy arrays: {array_time} seconds")

Time taken for element-wise addition using Python lists: 0.05190300941467285 seconds

Time taken for element-wise addition using Numpy arrays: 0.0026030540466308594 seconds


2. Element-wise Multiplication
- Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [82]:
list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

# measuring the time for element wise multiplication using Python lists
start_time = time.time()
result_time = [a*b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for element-wise multiplication using Python lists: {list_time} seconds")

# convert lists to numpy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# measuring time for element-wise multiplication using numpy arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
array_time = end_time - start_time
print(f"\nTime taken for element-wise multiplication using Numpy arrays: {array_time} seconds")

Time taken for element-wise multiplication using Python lists: 0.05964183807373047 seconds

Time taken for element-wise multiplication using Numpy arrays: 0.0009369850158691406 seconds


3. Dot Product
- Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
- Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [89]:
list1 = [i for i in range(1,1000001)]
list2 = [i for i in range(1000001,2000001)]

# measuring time for computing the dot product using Python lists
start_time = time.time()
result_time = [a*b for a,b in zip(list1, list2)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for computing the dot product using Python lists: {list_time} seconds")

# convert lists to numpy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# measuring time for computing the dot product using numpy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
array_time = end_time - start_time
print(f"\nTime taken for computing the dot product using Numpy arrays: {array_time} seconds")

Time taken for computing the dot product using Python lists: 0.042901039123535156 seconds

Time taken for computing the dot product using Numpy arrays: 0.0008254051208496094 seconds


4. Matrix Multiplication
- Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea- sure and print the time taken for this operation.
- Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [86]:
# size of matrix
N=1000

# initialize two matrices
matrix1 = [[i + j for j in range(N)] for i in range(N)]
matrix2 = [[i - j for j in range(N)] for i in range(N)]

# function to perform matrix multiplication of two matrices
def matrix_multiply(A,B):
  result = [[0] *N for _ in range(N)]
  for i in range(N):
    for j in range(N):
      for k in range(N):
        result[i][j] += A[i][k] * B[k][j]
  return result

# measuring time for matrix multiplication using Python lists
start_time = time.time()
result = matrix_multiply(matrix1, matrix2)
end_time = time.time()
execute_time = end_time - start_time
print(f"Time taken for matrix multiplication using Python lists: {execute_time} seconds")

# convert lists to numpy arrays
array1 = np.array(matrix1)
array2 = np.array(matrix2)

# measuring time for matrix multiplication using numpy arrays
start_time = time.time()
result_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"\nTime taken for matrix multiplication using Numpy arrays: {numpy_time:.6f} seconds")

Time taken for matrix multiplication using Python lists: 164.1737298965454 seconds

Time taken for matrix multiplication using Numpy arrays: 0.814291 seconds
